services:
  bot:
    image: leetgrindbot
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@leetgrindbot-v1-psql-1:5432/${DB_DATABASE}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GUILD_ID: ${GUILD_ID}
      CHANNEL_ID: ${CHANNEL_ID}
    depends_on:
      - psql
  psql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume: 
