version: '3.8'

services:
  bot:
    image: leetgrindbot
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    network_mode: "host"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GUILD_ID: ${GUILD_ID}
      CHANNEL_ID: ${CHANNEL_ID}
